### ISSUE TITLE
CID 22584: minus 20% morale based on loot calculation in expandloot

### ISSUE THREAD

**Issue by ennorehling** [eressea/server#326]
This is crazy bananas. I think the author meant to write * 1.2, not + 0.2 (which does nothing to these integers):

    /* Lowering morale by 1 depending on the looted money (+20%) */
    if (rng_int() % 100 < ((looted / startmoney) + 0.2)) {

**Comment by TurnerSE** [comment]
I might be wrong, but since "looted" should always be smaller than "startmoney", the division doesn't seem to be doing anything for those integers either, does it? Or am I interpreting those variables incorrectly?
What's the desired behaviour game-wise anyway? The ratio looted/startingmoney modified somehow by the 20% serves as a difficulty for the randomized condition to hit?

**Comment by ennorehling** [comment]
Der Code hat noch einen zweiten Report erzeugt:
CID 22461: Division or modulo by zero (DIVIDE_BY_ZERO)
divide_by_zero: In expression looted / startmoney, division by expression startmoney which may be zero has undefined behavior.

Das ist in der Praxis natürlich nie zero, aber das weiß die statissche Analyse ja nicht, und es kostet auch nicht, das zu checken und da einen Fehler zu loggen.

**Comment by TurnerSE** [comment]
Ich habe immer noch generelle Zweifel an der Division (s.o.). Wie stehen denn die Werte zueinander und wie ist das gewünschte Verhalten?

**Comment by ennorehling** [comment]
Das kann dir glaube ich nur CTD beantworten, der hat das geschrieben. Ich kenne die Regel selber nicht. Frag ihn mal auf der Mailingliste.

**Comment by ennorehling** [comment]
Mail mit aktuellem Stand zu der Frage ist raus an die Liste.

**Comment by stm2** [comment]
Ich vermute, die Absicht war,  dass die Wahrscheinlichkeit für das Fallen der Moral beim Plündern zwischen 20 % und 100 % liegt.

if (rng_int() % 100 < ((100 * looted / MAX(startmoney, 1)) + 20)) {
sollte funktionieren (wenn man es unbedingt in Integer-Arithmetik ausdrücken will).  Wobei ich mit MAX wahrscheinlich _max meine.

**Comment by CTD1** [comment]
Ja, das ist was ich angedacht habe, wobei ich einfach nur nicht daran gedacht habe das es ja ints sind.
Also entweder so, oder die Integer konvertieren.

**Comment by ennorehling** [comment]
Bei der Rechnugn von @stm2 liegt die Chance zwischen 20% und 120% (wenn looted == starmoney), ich glaube da muss mit 80 und nicht mit 100 skaliert werden.

**Comment by stm2** [comment]
Das kommt darauf an, was man will. Bei meiner Version ist die Chance 100%, wenn 80% des Regionssilbers geplündert werden. Bei dir müsste es also ...80 * looted... heißen und dann wäre 100% Chance erst wenn alles Silber geplündert wird. Macht keinen großen Unterschied.

**Comment by CTD1** [comment]
Von der Idee her war das schon so gewollt, ich hatte ursptünglich mit dem Gedankein gespielt das sogar noch zu erhöhen, so das z.B bei 40% Silberverlust die Chance schon bei 100% ist, auch wenn es dann sein kein da die Chance rechnerisch größer 100% wird, so ist das ja nicht schlimm.
