### ISSUE TITLE
coverity CID 22481: dereference after null check in save.c:1350

### ISSUE THREAD

**Issue by ennorehling** [eressea/server#331]
coverity complains about this code:
1349        int no = (sf->faction != NULL) ? sf->faction->no : 0;
1350        int status = alliedfaction(NULL, f, sf->faction, HELP_ALL);
 Dereference after null check (FORWARD_NULL)18. var_deref_model: Passing null pointer sf->faction to alliedfaction, which dereferences it.

we check for sf->faction==null in 1349, but if it was null, we cannot use it in 1350.

**Comment by TurnerSE** [comment]
Durch eressea/server#339 behoben.
