### ISSUE TITLE
coverity CID 22449: 'Constant' variable guards dead code (amphibian_level)

### ISSUE THREAD

**Issue by ennorehling** [eressea/server#337]
//  	assignment: Assigning: amphibian_level = 0.
531            int amphibian_level = 0;
532            if (u->ship || u_race(u) == get_race(RC_SPELL) || u->number == 0) {
533                up = &u->next;
534                continue;
535            }
536
//   	const: At condition amphibian_level, the value of amphibian_level must be equal to 0.
//   	dead_error_condition: The condition amphibian_level cannot be true.
537            if (amphibian_level) {
// CID 22449: 'Constant' variable guards dead code (DEADCODE)
// dead_error_begin: Execution cannot reach this statement: dead = damage_unit(u, "5d1"....

Local variable amphibian_level is assigned only once, to a constant value, making it effectively constant throughout its scope. If this is not the intent, examine the logic to see if there is a missing assignment that would make amphibian_level not remain constant.

**Comment by TurnerSE** [comment]
Sollte erledigt sein, nachdem nun der BugFix gemerged ist.
