### ISSUE TITLE
Refactoring of mechanics regarding spell airship

### ISSUE THREAD

**Issue by TurnerSE** [eressea/server#341]
@ennorehling in [Bug#1971](http://bugs.eressea.de/view.php?id=1971)
> Im übrigen könnte man hier mal ein Refactoring machen, und die Regeln von den fliegenden Schiffen in ein eigenes flyingship.c Modul auslagern. Das ist ziemlich standalone, und wäre einfacher zu überblicken, wenn der curse, der spell, und der Code in move.c alle dort hinein wandern würden.

Sollte vermutlich separat vom Bug als mögliche qualitative Verbesserung gehandhabt werden.

**Comment by ennorehling** [comment]
Man will ja so ein refactoring schon gerne vor dem Bugfix machen, das gehört für mich fast mit dazu :-) Immer den Code etwas schöner zurück lassen, als man ihn gefunden hat, etc.

**Comment by TurnerSE** [comment]
Habe mich hier für Divide&Conquer entschieden, weil ich für den tatsächlichen Bug eine schnelle Lösung hatte, aber das Refactoring meine Projektkenntnis doch deutlich strapaziert und erst einmal einiges an Bastelarbeit erfordern wird.
Ich bin jedenfalls dran. ;)

**Comment by ennorehling** [comment]
Ich habe das neulich erst für piracy.c gemacht. Der wichtigste Part is: Neue Dateien anlegen, in CMakeLists.txt eintragen, dann mit der .BAT Datei das Visual Studio Projekt neu erstellen. Dann den Code den man da hinein haben will rüberkopieren, in der .h Datei alles, was anderswo aufgerufen wird, deklarieren, und das include Statements in den Rest vom Code einbauen, damit es wieder kompiliert.

**Comment by TurnerSE** [comment]
Soll ich die Sachen aus shipcurse.c auch umziehen?
Das scheint schon recht spezialisiert zu sein (für Schiffsverzauberungen). Hab vorerst nur levitate_ship verlagert.

**Comment by ennorehling** [comment]
Ich finde, shipcurse.c ist ein kitchen sink von Funktionen, das ist gerade nicht spezialisert. Man kann theoretisch jeden Zauber als einzelnes Feature betrachten, und sich ein Spiel mit oder ohne dieses Feature denken. Die Verzauberung von Schiffen (shipcurse.c) ist eher kein Feature, und selbst wenn, nicht von fliegenden Schiffen abhängig. Ich würde also ct_flyingship und shipcurse_flyingship auch verlagern. levitate_ship braucht die ja, und die sind quasi private.

**Comment by TurnerSE** [comment]
Soll ich dann bei der Gelegenheit shipcurse komplett zerlegen?

**Comment by ennorehling** [comment]
Das ist zuviel des Guten, glaube ich. Man müsste das dann ja auch alles testen, usw. In Moderation das machen, was Deinen Bugfix betrifft, nicht einfach so Arbeit erzeugen, nur weil irgendwo der Code nicht schön ist (sonst wird man nie fertig).
