### ISSUE TITLE
seaserpent crashes piracy_cmd

### ISSUE THREAD

**Issue by ennorehling** [eressea/server#418]
call stack:
 	eressea.exe!can_takeoff(const ship * sh, const region * from, const region * to) Line 1769	C
	eressea.exe!piracy_cmd(unit * u, order * ord) Line 151	C
 	eressea.exe!move_pirates() Line 2483	C

caused by a recent change that makes sea serpents give piracy orders in version 3.8+
sea serpents have no ships, so piracy_cmd needs to deal with that.

**Comment by stm2** [comment]
Hm, da muss eine Seeschlange (oder was anderes Schwimmendes mit PIRATERIE-Befehl) an Land gewesen sein?
