### ISSUE TITLE
game.name in compress.py

### ISSUE THREAD

**Issue by ennorehling** [eressea/server#647]
right now, the game name (as used in the subject of outgoing reports) is pulled from eressea.ini by a clumsy grep in compress.sh. That has caused the mailpocalypse of turn 1011, and I fixed it rather poorly.
The correct thing to do would be for compress.py to use ConfigParser to read game.name, which is a much more robust solution.

**Comment by apexo** [comment]
This has been fixed in 45ec4b56df6e77722aca922034166beea30e3307.
